#!/bin/sh
docker run \
    --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
    -v $(pwd):/project/zerotooth \
    -it zerotooth-dev-env /bin/bash \
    -c 'cd /project/zerotooth; exec "${SHELL:-sh}"' 
